### ISSUE TITLE
Pack_manifest disappears

### ISSUE THREAD

**Issue by pipierti** [zfeikg/pocketshop#1]
I put your mod pocketshop in the corresponding folder and run miniworld, when I access the plugins folder the file pack_manifest is deleted from the folder and it is not found

**Comment by zfeikg** [comment]
Are you running Mini World Mobile or the PC Version? If you are in PC can you please provide an output of your `all.log` file? (in Windows is at ``miniworldoverseas`` folder in your ``%appdata%`` directory.)

**Comment by zfeikg** [comment]
It was just a JSON syntax error, try the new release [Commit - Fixes #1](https://github.com/zfeikg/pocketshop/commit/4357c4233b24d442298cf77b70f42bef19e0bc9b]
